export const LIVE_RUNTIME_WORKFLOW_ERROR_CODES = [
  "LIVE_WORKFLOW_TYPE_REQUIRED",
  "LIVE_WORKFLOW_SCOPE_INVALID",
  "LIVE_WORKFLOW_SCOPE_ID_REQUIRED",
  "LIVE_WORKFLOW_IDEMPOTENCY_KEY_REQUIRED",
  "LIVE_WORKFLOW_VERSION_INVALID",
  "LIVE_WORKFLOW_STEPS_REQUIRED",
  "LIVE_WORKFLOW_STEP_OBJECT_REQUIRED",
  "LIVE_WORKFLOW_STEP_KEY_REQUIRED",
  "LIVE_WORKFLOW_STEP_JOB_TYPE_REQUIRED",
  "LIVE_WORKFLOW_DEPENDENCY_NOT_FOUND",
  "LIVE_WORKFLOW_NOT_FOUND",
  "LIVE_WORKFLOW_ACCESS_DENIED",
  "LIVE_RUNTIME_WORKFLOW_EVENT_APPEND_ONLY",
] as const;

export type LiveRuntimeWorkflowErrorCode =
  (typeof LIVE_RUNTIME_WORKFLOW_ERROR_CODES)[number];

export function isLiveRuntimeWorkflowErrorCode(
  value: unknown,
): value is LiveRuntimeWorkflowErrorCode {
  return (
    typeof value === "string" &&
    (LIVE_RUNTIME_WORKFLOW_ERROR_CODES as readonly string[]).includes(value)
  );
}
