-- ============================================================================
-- FANTAGOL
-- Migration 041: Fantacalcio Preview Builder
--
-- Scope:
--   - freeze Fantacalcio Goals Profile v1 (threshold 23, constant step 10);
--   - version active League Scoring Profiles to schema_version 2;
--   - deterministic Fantacalcio Preview composition from an immutable
--     Points Preview Round Simulation;
--   - Attack / Defense strategic transformation from submitted snapshots;
--   - conversion of Fantacalcio points into goals;
--   - fixture preview generation without duplicating component-level scoring;
--   - authenticated member read RPC for the latest Fantacalcio Preview.
--
-- Out of scope:
--   - Prediction Resolution recalculation;
--   - One-to-One Preview;
--   - standings preview and ranking ledger;
--   - realtime publication and Live State orchestration;
--   - certification commit.
--
-- Architectural rule:
--   Each Preview Builder stores only the new knowledge generated by its own
--   transformation. Prediction components remain authoritative in the Points
--   Preview and are not duplicated in the Fantacalcio Preview.
-- ============================================================================

begin;

-- ============================================================================
-- 1. FANTACALCIO RULESET v2 AND GOALS PROFILE v1
-- ============================================================================

alter table public.league_scoring_profiles
  alter column fantacalcio_rules set default jsonb_build_object(
    'schema_version', 2,
    'attack_exact_multiplier', 2,
    'attack_opposite_sign_multiplier', 2,
    'attack_cantonata_multiplier', 2,
    'attack_surprise_multiplier', 2,
    'defence_malus_divisor', 2,
    'goal_profile', jsonb_build_object(
      'profile_version', 1,
      'type', 'constant_threshold',
      'base_points', 23,
      'step_points', 10,
      'base_goals', 0
    )
  );

-- Version every currently active profile instead of mutating its historical
-- rules. Existing Calculation Runs keep their original scoring_profile_id.
with deactivated as (
  update public.league_scoring_profiles lsp
  set active = false
  where lsp.active = true
    and not (
      coalesce((lsp.fantacalcio_rules ->> 'schema_version')::integer, 1) >= 2
      and lsp.fantacalcio_rules #>> '{goal_profile,base_points}' = '23'
      and lsp.fantacalcio_rules #>> '{goal_profile,step_points}' = '10'
    )
  returning lsp.*
)
insert into public.league_scoring_profiles (
  league_id,
  version,
  effective_from_league_round_id,
  exact_points,
  sign_points,
  over_under_points,
  goal_no_goal_points,
  surprise_bonus_enabled,
  goal_show_bonus_enabled,
  grand_slam_bonus_enabled,
  cantonata_malus_enabled,
  opposite_sign_malus_enabled,
  surprise_bonus_points,
  goal_show_bonus_points,
  grand_slam_bonus_points,
  cantonata_malus_points,
  opposite_sign_malus_points,
  fantacalcio_rules,
  one_to_one_rules,
  created_by_member_id,
  reason,
  active
)
select
  d.league_id,
  d.version + 1,
  d.effective_from_league_round_id,
  d.exact_points,
  d.sign_points,
  d.over_under_points,
  d.goal_no_goal_points,
  d.surprise_bonus_enabled,
  d.goal_show_bonus_enabled,
  d.grand_slam_bonus_enabled,
  d.cantonata_malus_enabled,
  d.opposite_sign_malus_enabled,
  d.surprise_bonus_points,
  d.goal_show_bonus_points,
  d.grand_slam_bonus_points,
  d.cantonata_malus_points,
  d.opposite_sign_malus_points,
  jsonb_build_object(
    'schema_version', 2,
    'attack_exact_multiplier',
      coalesce((d.fantacalcio_rules ->> 'attack_exact_multiplier')::numeric, 2),
    'attack_opposite_sign_multiplier',
      coalesce((d.fantacalcio_rules ->> 'attack_opposite_sign_multiplier')::numeric, 2),
    'attack_cantonata_multiplier',
      coalesce((d.fantacalcio_rules ->> 'attack_cantonata_multiplier')::numeric, 2),
    'attack_surprise_multiplier',
      coalesce((d.fantacalcio_rules ->> 'attack_surprise_multiplier')::numeric, 2),
    'defence_malus_divisor',
      coalesce((d.fantacalcio_rules ->> 'defence_malus_divisor')::numeric, 2),
    'goal_profile', jsonb_build_object(
      'profile_version', 1,
      'type', 'constant_threshold',
      'base_points', 23,
      'step_points', 10,
      'base_goals', 0
    )
  ),
  d.one_to_one_rules,
  d.created_by_member_id,
  'Fantacalcio Goals Profile v1: threshold 23, constant step 10',
  true
from deactivated d;

-- ============================================================================
-- 2. PURE POINTS-TO-GOALS CONVERTER
-- ============================================================================

create or replace function public.convert_fantacalcio_points_to_goals(
  p_points numeric,
  p_fantacalcio_rules jsonb
)
returns integer
language plpgsql
immutable
strict
security invoker
set search_path to public, pg_temp
as $function$
declare
  v_base_points numeric;
  v_step_points numeric;
  v_base_goals integer;
begin
  if jsonb_typeof(p_fantacalcio_rules) <> 'object' then
    raise exception using
      errcode = 'P0001',
      message = 'FANTACALCIO_RULES_INVALID';
  end if;

  v_base_points := coalesce(
    (p_fantacalcio_rules #>> '{goal_profile,base_points}')::numeric,
    23
  );
  v_step_points := coalesce(
    (p_fantacalcio_rules #>> '{goal_profile,step_points}')::numeric,
    10
  );
  v_base_goals := coalesce(
    (p_fantacalcio_rules #>> '{goal_profile,base_goals}')::integer,
    0
  );

  if v_base_points < 0 or v_step_points <= 0 or v_base_goals < 0 then
    raise exception using
      errcode = 'P0001',
      message = 'FANTACALCIO_GOAL_PROFILE_INVALID';
  end if;

  if p_points < v_base_points then
    return v_base_goals;
  end if;

  return v_base_goals
    + 1
    + floor((p_points - v_base_points) / v_step_points)::integer;
end;
$function$;

-- ============================================================================
-- 3. FANTACALCIO PREVIEW BUILDER
-- ============================================================================

create or replace function public.build_fantacalcio_preview_simulation_rpc(
  p_source_simulation_id uuid,
  p_simulation_engine_version text default 'round-simulation-v1-fantacalcio-v1',
  p_created_by_member_id uuid default null,
  p_correlation_id uuid default null
)
returns table (
  simulation_id uuid,
  source_simulation_id uuid,
  league_round_id uuid,
  calculation_run_id uuid,
  simulation_version integer,
  simulation_status text,
  builder_status text,
  fixture_count integer,
  complete_fixture_count integer,
  pending_fixture_count integer,
  input_hash text,
  output_hash text,
  simulation_hash text
)
language plpgsql
security definer
set search_path to public, pg_temp
as $function$
declare
  v_source public.round_simulations%rowtype;
  v_existing public.round_simulations%rowtype;
  v_simulation public.round_simulations%rowtype;
  v_builder public.round_simulation_builder_runs%rowtype;
  v_run public.round_calculation_runs%rowtype;
  v_round public.league_rounds%rowtype;
  v_profile public.league_scoring_profiles%rowtype;

  v_rules jsonb;
  v_simulation_version integer;
  v_fixture_count integer;
  v_complete_fixture_count integer;
  v_pending_fixture_count integer;
  v_correlation_id uuid;

  v_input_manifest jsonb;
  v_fixtures jsonb;
  v_member_results jsonb;
  v_fantacalcio_preview jsonb;
  v_digital_twin jsonb;

  v_input_hash text;
  v_builder_output_hash text;
  v_output_hash text;
  v_simulation_hash text;
begin
  if p_source_simulation_id is null then
    raise exception using
      errcode = 'P0001',
      message = 'SOURCE_SIMULATION_REQUIRED';
  end if;

  if nullif(btrim(p_simulation_engine_version), '') is null then
    raise exception using
      errcode = 'P0001',
      message = 'SIMULATION_ENGINE_VERSION_REQUIRED';
  end if;

  select rs.*
  into v_source
  from public.round_simulations rs
  where rs.id = p_source_simulation_id;

  if not found then
    raise exception using
      errcode = 'P0001',
      message = 'SOURCE_SIMULATION_NOT_FOUND';
  end if;

  if v_source.status not in ('preview_ready', 'awaiting_certification', 'certified')
     or not (v_source.digital_twin ? 'points_preview') then
    raise exception using
      errcode = 'P0001',
      message = 'SOURCE_POINTS_PREVIEW_NOT_READY',
      detail = v_source.status;
  end if;

  select rcr.*
  into v_run
  from public.round_calculation_runs rcr
  where rcr.id = v_source.calculation_run_id;

  if not found then
    raise exception using
      errcode = 'P0001',
      message = 'CALCULATION_RUN_NOT_FOUND';
  end if;

  select lr.*
  into v_round
  from public.league_rounds lr
  where lr.id = v_source.league_round_id;

  if not found then
    raise exception using
      errcode = 'P0001',
      message = 'LEAGUE_ROUND_NOT_FOUND';
  end if;

  if p_created_by_member_id is not null
     and not exists (
       select 1
       from public.league_members lm
       where lm.id = p_created_by_member_id
         and lm.league_id = v_round.league_id
         and lm.status = 'active'
     ) then
    raise exception using
      errcode = 'P0001',
      message = 'CREATOR_MEMBERSHIP_INVALID';
  end if;

  select lsp.*
  into v_profile
  from public.league_scoring_profiles lsp
  where lsp.id = v_run.scoring_profile_id;

  if not found then
    raise exception using
      errcode = 'P0001',
      message = 'SCORING_PROFILE_NOT_FOUND';
  end if;

  -- Old Calculation Runs may reference the historical v1 profile. The frozen
  -- v1 Goals Profile is added as a deterministic fallback without altering
  -- the source profile snapshot.
  v_rules := jsonb_build_object(
    'schema_version', 2,
    'attack_exact_multiplier',
      coalesce((v_profile.fantacalcio_rules ->> 'attack_exact_multiplier')::numeric, 2),
    'attack_opposite_sign_multiplier',
      coalesce((v_profile.fantacalcio_rules ->> 'attack_opposite_sign_multiplier')::numeric, 2),
    'attack_cantonata_multiplier',
      coalesce((v_profile.fantacalcio_rules ->> 'attack_cantonata_multiplier')::numeric, 2),
    'attack_surprise_multiplier',
      coalesce((v_profile.fantacalcio_rules ->> 'attack_surprise_multiplier')::numeric, 2),
    'defence_malus_divisor',
      coalesce((v_profile.fantacalcio_rules ->> 'defence_malus_divisor')::numeric, 2),
    'goal_profile', coalesce(
      v_profile.fantacalcio_rules -> 'goal_profile',
      jsonb_build_object(
        'profile_version', 1,
        'type', 'constant_threshold',
        'base_points', 23,
        'step_points', 10,
        'base_goals', 0
      )
    )
  );

  if (v_rules ->> 'attack_exact_multiplier')::numeric <= 0
     or (v_rules ->> 'attack_surprise_multiplier')::numeric <= 0
     or (v_rules ->> 'attack_opposite_sign_multiplier')::numeric <= 0
     or (v_rules ->> 'attack_cantonata_multiplier')::numeric <= 0
     or (v_rules ->> 'defence_malus_divisor')::numeric <= 0 then
    raise exception using
      errcode = 'P0001',
      message = 'FANTACALCIO_RULES_INVALID';
  end if;

  -- Idempotent fast path.
  select rs.*
  into v_existing
  from public.round_simulations rs
  where rs.league_round_id = v_round.id
    and rs.calculation_run_id = v_run.id
    and rs.engine_version = p_simulation_engine_version
  limit 1;

  if found then
    if v_existing.status in ('preview_ready', 'awaiting_certification', 'certified')
       and v_existing.digital_twin ? 'fantacalcio_preview' then
      return query
      select
        v_existing.id,
        p_source_simulation_id,
        v_existing.league_round_id,
        v_existing.calculation_run_id,
        v_existing.simulation_version,
        v_existing.status,
        coalesce(
          (
            select sbr.status
            from public.round_simulation_builder_runs sbr
            where sbr.simulation_id = v_existing.id
              and sbr.builder_name = 'FantacalcioPreviewBuilder'
            limit 1
          ),
          'completed'
        ),
        coalesce(
          jsonb_array_length(v_existing.digital_twin #> '{fantacalcio_preview,fixtures}'),
          0
        ),
        coalesce(
          (v_existing.digital_twin #>> '{fantacalcio_preview,complete_fixture_count}')::integer,
          0
        ),
        coalesce(
          (v_existing.digital_twin #>> '{fantacalcio_preview,pending_fixture_count}')::integer,
          0
        ),
        v_existing.input_hash,
        v_existing.output_hash,
        v_existing.simulation_hash;
      return;
    end if;

    raise exception using
      errcode = 'P0001',
      message = 'FANTACALCIO_SIMULATION_EXISTING_NOT_REUSABLE',
      detail = v_existing.status;
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended(
      'fantacalcio-preview-simulation:' || v_round.id::text,
      0
    )
  );

  select rs.*
  into v_existing
  from public.round_simulations rs
  where rs.league_round_id = v_round.id
    and rs.calculation_run_id = v_run.id
    and rs.engine_version = p_simulation_engine_version
  limit 1;

  if found then
    if v_existing.status in ('preview_ready', 'awaiting_certification', 'certified')
       and v_existing.digital_twin ? 'fantacalcio_preview' then
      return query
      select
        v_existing.id,
        p_source_simulation_id,
        v_existing.league_round_id,
        v_existing.calculation_run_id,
        v_existing.simulation_version,
        v_existing.status,
        'completed'::text,
        coalesce(
          jsonb_array_length(v_existing.digital_twin #> '{fantacalcio_preview,fixtures}'),
          0
        ),
        coalesce(
          (v_existing.digital_twin #>> '{fantacalcio_preview,complete_fixture_count}')::integer,
          0
        ),
        coalesce(
          (v_existing.digital_twin #>> '{fantacalcio_preview,pending_fixture_count}')::integer,
          0
        ),
        v_existing.input_hash,
        v_existing.output_hash,
        v_existing.simulation_hash;
      return;
    end if;

    raise exception using
      errcode = 'P0001',
      message = 'FANTACALCIO_SIMULATION_EXISTING_NOT_REUSABLE',
      detail = v_existing.status;
  end if;

  if exists (
    select 1
    from public.round_simulations rs
    where rs.league_round_id = v_round.id
      and rs.publishable = true
      and rs.status in ('awaiting_certification', 'certified')
      and rs.id <> v_source.id
  ) then
    raise exception using
      errcode = 'P0001',
      message = 'CURRENT_SIMULATION_NOT_REPLACEABLE';
  end if;

  select count(*)::integer
  into v_fixture_count
  from public.league_fixtures lf
  where lf.league_round_id = v_round.id
    and lf.mode = 'fantacalcio';

  if v_fixture_count = 0 then
    raise exception using
      errcode = 'P0001',
      message = 'FANTACALCIO_FIXTURES_EMPTY';
  end if;

  select coalesce(max(rs.simulation_version), 0) + 1
  into v_simulation_version
  from public.round_simulations rs
  where rs.league_round_id = v_round.id;

  v_correlation_id := coalesce(p_correlation_id, v_source.correlation_id, gen_random_uuid());

  v_input_manifest := jsonb_build_object(
    'schema_version', 1,
    'simulation_engine', 'RoundSimulationEngine',
    'simulation_engine_version', p_simulation_engine_version,
    'builder_name', 'FantacalcioPreviewBuilder',
    'builder_version', 'fantacalcio-preview-v1',
    'source_simulation_id', v_source.id,
    'source_simulation_version', v_source.simulation_version,
    'source_simulation_hash', v_source.simulation_hash,
    'league_round_id', v_round.id,
    'calculation_run_id', v_run.id,
    'scoring_profile_id', v_profile.id,
    'scoring_profile_version', v_profile.version,
    'fantacalcio_rules', v_rules
  );

  v_input_hash := public.compute_jsonb_sha256(v_input_manifest);

  insert into public.round_simulations (
    league_round_id,
    calculation_run_id,
    simulation_version,
    engine_version,
    snapshot_schema_version,
    status,
    preview,
    publishable,
    digital_twin,
    input_hash,
    correlation_id,
    created_by_member_id
  )
  values (
    v_round.id,
    v_run.id,
    v_simulation_version,
    p_simulation_engine_version,
    1,
    'building',
    true,
    false,
    '{}'::jsonb,
    v_input_hash,
    v_correlation_id,
    p_created_by_member_id
  )
  returning * into v_simulation;

  insert into public.round_simulation_events (
    simulation_id,
    league_round_id,
    calculation_run_id,
    event_type,
    payload,
    correlation_id,
    actor_member_id
  )
  values (
    v_simulation.id,
    v_round.id,
    v_run.id,
    'RoundSimulationBuilding',
    jsonb_build_object(
      'simulation_version', v_simulation_version,
      'engine_version', p_simulation_engine_version,
      'source_simulation_id', v_source.id,
      'builder', 'FantacalcioPreviewBuilder'
    ),
    v_correlation_id,
    p_created_by_member_id
  );

  -- Register the inherited Points Preview as an already completed dependency.
  insert into public.round_simulation_builder_runs (
    simulation_id,
    builder_name,
    builder_version,
    builder_order,
    required,
    status,
    started_at,
    completed_at,
    input_hash,
    output_hash,
    metadata
  )
  values (
    v_simulation.id,
    'PointsPreviewBuilder',
    'points-preview-v1',
    1,
    true,
    'completed',
    v_source.created_at,
    coalesce(v_source.completed_at, v_source.created_at),
    v_source.input_hash,
    coalesce(
      (
        select sbr.output_hash
        from public.round_simulation_builder_runs sbr
        where sbr.simulation_id = v_source.id
          and sbr.builder_name = 'PointsPreviewBuilder'
        limit 1
      ),
      public.compute_jsonb_sha256(v_source.digital_twin -> 'points_preview')
    ),
    jsonb_build_object(
      'inherited', true,
      'source_simulation_id', v_source.id
    )
  );

  insert into public.round_simulation_builder_runs (
    simulation_id,
    builder_name,
    builder_version,
    builder_order,
    required,
    status,
    started_at,
    input_hash,
    metadata
  )
  values (
    v_simulation.id,
    'FantacalcioPreviewBuilder',
    'fantacalcio-preview-v1',
    2,
    true,
    'running',
    clock_timestamp(),
    v_input_hash,
    jsonb_build_object(
      'source_simulation_id', v_source.id,
      'fixture_count', v_fixture_count,
      'goal_profile', v_rules -> 'goal_profile'
    )
  )
  returning * into v_builder;

  -- Build member final points/goals. Missing or invalid official strategies do
  -- not invent a fallback allocation: the member remains pending.
  with fixture_members as (
    select
      lf.id as fixture_id,
      lf.home_member_id as league_member_id,
      'home'::text as fixture_side
    from public.league_fixtures lf
    where lf.league_round_id = v_round.id
      and lf.mode = 'fantacalcio'
      and not lf.is_bye

    union all

    select
      lf.id,
      lf.away_member_id,
      'away'::text
    from public.league_fixtures lf
    where lf.league_round_id = v_round.id
      and lf.mode = 'fantacalcio'
      and not lf.is_bye
      and lf.away_member_id is not null
  ), official_strategies as (
    select
      s.league_fixture_id as fixture_id,
      s.league_member_id,
      s.id as strategy_id,
      s.submitted_version as strategy_version,
      sv.payload
    from public.strategies s
    join public.strategy_versions sv
      on sv.strategy_id = s.id
     and sv.version = s.submitted_version
    join public.league_fixtures lf
      on lf.id = s.league_fixture_id
    where s.league_round_id = v_round.id
      and lf.mode = 'fantacalcio'
      and s.submitted_version is not null
      and s.status in ('submitted', 'locked')
      and sv.status in ('submitted', 'locked')
      and jsonb_typeof(sv.payload -> 'allocations') = 'array'
  ), allocation_rows as (
    select
      os.fixture_id,
      os.league_member_id,
      os.strategy_id,
      os.strategy_version,
      a.match_id,
      a.department
    from official_strategies os
    cross join lateral (
      select
        (x ->> 'match_id')::uuid as match_id,
        x ->> 'department' as department
      from jsonb_array_elements(os.payload -> 'allocations') x
      where x ? 'match_id'
        and x ? 'department'
    ) a
  ), strategy_validation as (
    select
      os.fixture_id,
      os.league_member_id,
      os.strategy_id,
      os.strategy_version,
      count(ar.match_id)::integer as allocation_count,
      count(distinct ar.match_id)::integer as distinct_match_count,
      count(*) filter (where ar.department = 'attack')::integer as attack_count,
      count(*) filter (where ar.department = 'defense')::integer as defense_count,
      bool_and(ar.department in ('attack', 'defense')) as departments_valid,
      (
        count(ar.match_id) = 10
        and count(distinct ar.match_id) = 10
        and count(*) filter (where ar.department = 'attack') = 5
        and count(*) filter (where ar.department = 'defense') = 5
        and bool_and(ar.department in ('attack', 'defense'))
      ) as strategy_valid
    from official_strategies os
    left join allocation_rows ar
      on ar.fixture_id = os.fixture_id
     and ar.league_member_id = os.league_member_id
    group by
      os.fixture_id,
      os.league_member_id,
      os.strategy_id,
      os.strategy_version
  ), member_scores as (
    select
      fm.fixture_id,
      fm.league_member_id,
      fm.fixture_side,
      sv.strategy_id,
      sv.strategy_version,
      coalesce(sv.strategy_valid, false) as strategy_valid,
      case
        when coalesce(sv.strategy_valid, false) then
          sum(
            case
              when ar.department = 'attack' then
                psrr.base_total
                + psrr.exact_points
                  * ((v_rules ->> 'attack_exact_multiplier')::numeric - 1)
                + psrr.surprise_points
                  * ((v_rules ->> 'attack_surprise_multiplier')::numeric - 1)
                + psrr.opposite_sign_points
                  * ((v_rules ->> 'attack_opposite_sign_multiplier')::numeric - 1)
                + psrr.cantonata_points
                  * ((v_rules ->> 'attack_cantonata_multiplier')::numeric - 1)
              when ar.department = 'defense' then
                psrr.base_total
                - psrr.opposite_sign_points
                - psrr.cantonata_points
                + psrr.opposite_sign_points
                  / (v_rules ->> 'defence_malus_divisor')::numeric
                + psrr.cantonata_points
                  / (v_rules ->> 'defence_malus_divisor')::numeric
              else 0
            end
          )::numeric(12,2)
        else null
      end as fantacalcio_points,
      case
        when coalesce(sv.strategy_valid, false) then bool_or(psrr.provisional)
        else true
      end as provisional
    from fixture_members fm
    left join strategy_validation sv
      on sv.fixture_id = fm.fixture_id
     and sv.league_member_id = fm.league_member_id
    left join allocation_rows ar
      on ar.fixture_id = fm.fixture_id
     and ar.league_member_id = fm.league_member_id
    left join public.prediction_score_runtime_results psrr
      on psrr.calculation_run_id = v_run.id
     and psrr.league_member_id = fm.league_member_id
     and psrr.match_id = ar.match_id
    group by
      fm.fixture_id,
      fm.league_member_id,
      fm.fixture_side,
      sv.strategy_id,
      sv.strategy_version,
      sv.strategy_valid
  ), scored_members as (
    select
      ms.*,
      case
        when ms.strategy_valid and ms.fantacalcio_points is not null then
          public.convert_fantacalcio_points_to_goals(
            ms.fantacalcio_points,
            v_rules
          )
        else null
      end as goals
    from member_scores ms
  )
  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'fixture_id', sm.fixture_id,
        'league_member_id', sm.league_member_id,
        'fixture_side', sm.fixture_side,
        'strategy_id', sm.strategy_id,
        'strategy_version', sm.strategy_version,
        'strategy_valid', sm.strategy_valid,
        'points', sm.fantacalcio_points,
        'goals', sm.goals,
        'provisional', sm.provisional
      )
      order by sm.fixture_id, sm.fixture_side
    ),
    '[]'::jsonb
  )
  into v_member_results
  from scored_members sm;

  with member_rows as (
    select
      (x ->> 'fixture_id')::uuid as fixture_id,
      x ->> 'fixture_side' as fixture_side,
      (x ->> 'league_member_id')::uuid as league_member_id,
      nullif(x ->> 'strategy_id', '')::uuid as strategy_id,
      nullif(x ->> 'strategy_version', '')::integer as strategy_version,
      coalesce((x ->> 'strategy_valid')::boolean, false) as strategy_valid,
      nullif(x ->> 'points', '')::numeric as points,
      nullif(x ->> 'goals', '')::integer as goals,
      coalesce((x ->> 'provisional')::boolean, true) as provisional
    from jsonb_array_elements(v_member_results) x
  ), fixture_rows as (
    select
      lf.id as fixture_id,
      lf.cycle_number,
      lf.leg_number,
      lf.pairing_round_number,
      lf.home_member_id,
      lf.away_member_id,
      lf.is_bye,
      hm.display_name as home_display_name,
      am.display_name as away_display_name,
      h.strategy_id as home_strategy_id,
      h.strategy_version as home_strategy_version,
      h.strategy_valid as home_strategy_valid,
      h.points as home_points,
      h.goals as home_goals,
      a.strategy_id as away_strategy_id,
      a.strategy_version as away_strategy_version,
      a.strategy_valid as away_strategy_valid,
      a.points as away_points,
      a.goals as away_goals,
      coalesce(h.provisional, true) or coalesce(a.provisional, true) as provisional,
      case
        when lf.is_bye then 'bye'
        when coalesce(h.strategy_valid, false)
         and coalesce(a.strategy_valid, false)
         and h.goals is not null
         and a.goals is not null then 'ready'
        else 'strategy_incomplete'
      end as fixture_phase
    from public.league_fixtures lf
    join public.league_members hm
      on hm.id = lf.home_member_id
    left join public.league_members am
      on am.id = lf.away_member_id
    left join member_rows h
      on h.fixture_id = lf.id
     and h.fixture_side = 'home'
    left join member_rows a
      on a.fixture_id = lf.id
     and a.fixture_side = 'away'
    where lf.league_round_id = v_round.id
      and lf.mode = 'fantacalcio'
  )
  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'fixture_id', fr.fixture_id,
        'mode', 'fantacalcio',
        'cycle_number', fr.cycle_number,
        'leg_number', fr.leg_number,
        'pairing_round_number', fr.pairing_round_number,
        'is_bye', fr.is_bye,
        'fixture_phase', fr.fixture_phase,
        'provisional', fr.provisional,
        'home', jsonb_build_object(
          'member_id', fr.home_member_id,
          'display_name', fr.home_display_name,
          'strategy_id', fr.home_strategy_id,
          'strategy_version', fr.home_strategy_version,
          'strategy_valid', coalesce(fr.home_strategy_valid, false),
          'points', fr.home_points,
          'goals', fr.home_goals
        ),
        'away', case
          when fr.away_member_id is null then null
          else jsonb_build_object(
            'member_id', fr.away_member_id,
            'display_name', fr.away_display_name,
            'strategy_id', fr.away_strategy_id,
            'strategy_version', fr.away_strategy_version,
            'strategy_valid', coalesce(fr.away_strategy_valid, false),
            'points', fr.away_points,
            'goals', fr.away_goals
          )
        end,
        'result', case
          when fr.fixture_phase <> 'ready' then null
          else jsonb_build_object(
            'home_goals', fr.home_goals,
            'away_goals', fr.away_goals,
            'goal_difference', fr.home_goals - fr.away_goals,
            'winner', case
              when fr.home_goals > fr.away_goals then 'home'
              when fr.home_goals < fr.away_goals then 'away'
              else 'draw'
            end
          )
        end
      )
      order by fr.pairing_round_number, fr.fixture_id
    ),
    '[]'::jsonb
  )
  into v_fixtures
  from fixture_rows fr;

  select
    count(*) filter (
      where x ->> 'fixture_phase' in ('ready', 'bye')
    )::integer,
    count(*) filter (
      where x ->> 'fixture_phase' = 'strategy_incomplete'
    )::integer
  into v_complete_fixture_count, v_pending_fixture_count
  from jsonb_array_elements(v_fixtures) x;

  v_fantacalcio_preview := jsonb_build_object(
    'schema_version', 1,
    'builder', 'FantacalcioPreviewBuilder',
    'builder_version', 'fantacalcio-preview-v1',
    'source_simulation_id', v_source.id,
    'scoring_profile_id', v_profile.id,
    'scoring_profile_version', v_profile.version,
    'goal_profile', v_rules -> 'goal_profile',
    'fixture_count', v_fixture_count,
    'complete_fixture_count', v_complete_fixture_count,
    'pending_fixture_count', v_pending_fixture_count,
    'fixtures', v_fixtures
  );

  v_builder_output_hash := public.compute_jsonb_sha256(v_fantacalcio_preview);

  v_digital_twin := jsonb_set(
    v_source.digital_twin,
    '{fantacalcio_preview}',
    v_fantacalcio_preview,
    true
  );

  v_digital_twin := jsonb_set(
    v_digital_twin,
    '{manifest}',
    (v_digital_twin -> 'manifest') || jsonb_build_object(
      'engine_version', p_simulation_engine_version,
      'simulation_id', v_simulation.id,
      'simulation_version', v_simulation_version,
      'source_simulation_id', v_source.id,
      'source_simulation_hash', v_source.simulation_hash,
      'fantacalcio_preview_hash', v_builder_output_hash,
      'fantacalcio_rules_schema_version', 2,
      'goal_profile_version', 1
    ),
    true
  );

  v_output_hash := public.compute_jsonb_sha256(v_digital_twin);
  v_simulation_hash := encode(
    extensions.digest(
      v_input_hash || ':' || v_output_hash,
      'sha256'
    ),
    'hex'
  );

  update public.round_simulation_builder_runs sbr
  set
    status = 'completed',
    completed_at = clock_timestamp(),
    output_hash = v_builder_output_hash,
    metadata = sbr.metadata || jsonb_build_object(
      'complete_fixture_count', v_complete_fixture_count,
      'pending_fixture_count', v_pending_fixture_count
    )
  where sbr.id = v_builder.id
  returning * into v_builder;

  insert into public.round_simulation_events (
    simulation_id,
    league_round_id,
    calculation_run_id,
    event_type,
    payload,
    correlation_id,
    causation_id,
    actor_member_id
  )
  values (
    v_simulation.id,
    v_round.id,
    v_run.id,
    'SimulationBuilderCompleted',
    jsonb_build_object(
      'builder_name', v_builder.builder_name,
      'builder_version', v_builder.builder_version,
      'builder_output_hash', v_builder_output_hash,
      'fixture_count', v_fixture_count,
      'complete_fixture_count', v_complete_fixture_count,
      'pending_fixture_count', v_pending_fixture_count
    ),
    v_correlation_id,
    v_builder.id,
    p_created_by_member_id
  );

  -- The derived Digital Twin supersedes only the replaceable Points Preview.
  update public.round_simulations rs
  set
    status = 'preview_invalidated',
    publishable = false,
    invalidated_at = clock_timestamp(),
    invalidation_reason = 'superseded_by_fantacalcio_preview'
  where rs.id = v_source.id
    and rs.publishable = true
    and rs.status = 'preview_ready';

  update public.round_simulations rs
  set
    status = 'preview_ready',
    preview = true,
    publishable = true,
    digital_twin = v_digital_twin,
    input_hash = v_input_hash,
    output_hash = v_output_hash,
    simulation_hash = v_simulation_hash,
    completed_at = clock_timestamp(),
    failed_at = null,
    failure_details = null
  where rs.id = v_simulation.id
  returning * into v_simulation;

  insert into public.round_simulation_events (
    simulation_id,
    league_round_id,
    calculation_run_id,
    event_type,
    payload,
    correlation_id,
    actor_member_id
  )
  values (
    v_simulation.id,
    v_round.id,
    v_run.id,
    'RoundSimulationReady',
    jsonb_build_object(
      'simulation_version', v_simulation.simulation_version,
      'simulation_hash', v_simulation.simulation_hash,
      'builders_completed', jsonb_build_array(
        'PointsPreviewBuilder',
        'FantacalcioPreviewBuilder'
      )
    ),
    v_correlation_id,
    p_created_by_member_id
  );

  return query
  select
    v_simulation.id,
    v_source.id,
    v_simulation.league_round_id,
    v_simulation.calculation_run_id,
    v_simulation.simulation_version,
    v_simulation.status,
    v_builder.status,
    v_fixture_count,
    v_complete_fixture_count,
    v_pending_fixture_count,
    v_simulation.input_hash,
    v_simulation.output_hash,
    v_simulation.simulation_hash;

exception
  when others then
    if v_builder.id is not null then
      update public.round_simulation_builder_runs sbr
      set
        status = 'failed',
        completed_at = clock_timestamp(),
        error_code = sqlstate,
        error_message = sqlerrm
      where sbr.id = v_builder.id;
    end if;

    if v_simulation.id is not null then
      update public.round_simulations rs
      set
        status = 'failed',
        publishable = false,
        failed_at = clock_timestamp(),
        failure_details = jsonb_build_object(
          'sqlstate', sqlstate,
          'message', sqlerrm,
          'source_simulation_id', p_source_simulation_id
        )
      where rs.id = v_simulation.id
        and rs.status = 'building';
    end if;

    raise;
end;
$function$;

-- ============================================================================
-- 4. AUTHENTICATED MEMBER READ RPC
-- ============================================================================

create or replace function public.get_my_fantacalcio_preview_rpc(
  p_league_round_id uuid
)
returns table (
  simulation_id uuid,
  simulation_version integer,
  simulation_status text,
  simulation_hash text,
  manifest jsonb,
  round_view jsonb,
  matches jsonb,
  fixture jsonb
)
language plpgsql
stable
security definer
set search_path to public, pg_temp
as $function$
declare
  v_user_id uuid;
  v_member_id uuid;
  v_simulation public.latest_round_simulation_v%rowtype;
begin
  v_user_id := auth.uid();

  if v_user_id is null then
    raise exception using
      errcode = 'P0001',
      message = 'AUTHENTICATION_REQUIRED';
  end if;

  select lm.id
  into v_member_id
  from public.league_rounds lr
  join public.league_members lm
    on lm.league_id = lr.league_id
  where lr.id = p_league_round_id
    and lm.user_id = v_user_id
    and lm.status = 'active'
  limit 1;

  if v_member_id is null then
    raise exception using
      errcode = 'P0001',
      message = 'ACTIVE_LEAGUE_MEMBERSHIP_REQUIRED';
  end if;

  select lrs.*
  into v_simulation
  from public.latest_round_simulation_v lrs
  where lrs.league_round_id = p_league_round_id
    and lrs.digital_twin ? 'fantacalcio_preview'
  limit 1;

  if not found then
    return;
  end if;

  return query
  select
    v_simulation.simulation_id,
    v_simulation.simulation_version,
    v_simulation.status,
    v_simulation.simulation_hash,
    v_simulation.digital_twin -> 'manifest',
    v_simulation.digital_twin -> 'round',
    v_simulation.digital_twin -> 'matches',
    coalesce(
      (
        select x
        from jsonb_array_elements(
          v_simulation.digital_twin #> '{fantacalcio_preview,fixtures}'
        ) x
        where (x #>> '{home,member_id}')::uuid = v_member_id
           or nullif(x #>> '{away,member_id}', '')::uuid = v_member_id
        limit 1
      ),
      '{}'::jsonb
    );
end;
$function$;

-- ============================================================================
-- 5. GRANTS
-- ============================================================================

revoke all on function public.convert_fantacalcio_points_to_goals(
  numeric,
  jsonb
) from public;

revoke all on function public.convert_fantacalcio_points_to_goals(
  numeric,
  jsonb
) from anon;

revoke all on function public.convert_fantacalcio_points_to_goals(
  numeric,
  jsonb
) from authenticated;

grant execute on function public.convert_fantacalcio_points_to_goals(
  numeric,
  jsonb
) to service_role;

revoke all on function public.build_fantacalcio_preview_simulation_rpc(
  uuid,
  text,
  uuid,
  uuid
) from public;

revoke all on function public.build_fantacalcio_preview_simulation_rpc(
  uuid,
  text,
  uuid,
  uuid
) from anon;

revoke all on function public.build_fantacalcio_preview_simulation_rpc(
  uuid,
  text,
  uuid,
  uuid
) from authenticated;

grant execute on function public.build_fantacalcio_preview_simulation_rpc(
  uuid,
  text,
  uuid,
  uuid
) to service_role;

revoke all on function public.get_my_fantacalcio_preview_rpc(uuid)
  from public;
revoke all on function public.get_my_fantacalcio_preview_rpc(uuid)
  from anon;
revoke all on function public.get_my_fantacalcio_preview_rpc(uuid)
  from service_role;

grant execute on function public.get_my_fantacalcio_preview_rpc(uuid)
  to authenticated;

-- ============================================================================
-- 6. COMMENTS
-- ============================================================================

comment on function public.convert_fantacalcio_points_to_goals(
  numeric,
  jsonb
) is
'Converts Fantacalcio strategic points into goals using the versioned constant-threshold profile. Official v1: 0 goals below 23, then one additional goal every 10 points.';

comment on function public.build_fantacalcio_preview_simulation_rpc(
  uuid,
  text,
  uuid,
  uuid
) is
'Builds a new immutable Round Simulation derived from a ready Points Preview. Applies submitted 5 Attack / 5 Defense Strategy Snapshots and stores only final Fantacalcio points, goals and fixture result. Service-role only.';

comment on function public.get_my_fantacalcio_preview_rpc(uuid) is
'Returns the authenticated member latest Fantacalcio fixture preview. The client receives final points and goals, not internal Attack/Defense component calculations.';

commit;
